ripgrep_version: 14.0.1
ripgrep_deb_version: 1
ripgrep_url: "https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep_{{ ripgrep_version }}-{{ ripgrep_deb_version }}_amd64.deb"
